language: node_js
node_js:
  - "4.2.4"
env:
  - YENV=production
install:
  - npm install
  - enb make
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd common.bundles/index
    git clone --single-branch -b gh-pages https://github.com/aliosv/cryptex.git
    cp _index.js cryptex
    cp _index.css cryptex
    cp index.html cryptex
    cp -r ../../i/ cryptex
    cd cryptex
    git add --all
    git -c user.name='travis' -c user.email='travis' commit -m $TRAVIS_COMMIT
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://aliosv:$GITHUB_API_KEY@github.com/aliosv/cryptex gh-pages
    cd "$TRAVIS_BUILD_DIR"
  fi
